# Generated by Django 4.2.2 on 2023-06-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descuento',
            field=models.SmallIntegerField(default=0),
        ),
    ]
