# Generated by Django 4.2.2 on 2023-06-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0002_libro_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.CharField(default='', max_length=255),
        ),
    ]
