# Generated by Django 4.2.2 on 2023-06-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0003_libro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(default='', max_length=50),
        ),
    ]
